name: PR Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Unit tests (coverage)
        working-directory: backend
        run: npm test -- --coverage

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: backend/coverage
          retention-days: 5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Auto-format instead of -check so PRs don't fail on fmt
      - name: Terraform fmt (auto)
        working-directory: infra/terraform
        run: terraform fmt -recursive

      # Don't talk to the S3 backend in PR checks
      - name: Terraform init (no backend)
        working-directory: infra/terraform
        run: terraform init -backend=false -input=false

      - name: Terraform validate
        working-directory: infra/terraform
        run: terraform validate

      # Offline plan with dummy creds so AWS provider doesn't complain
      - name: Terraform plan (offline)
        env:
          TF_VAR_ci: true
          TF_VAR_aws_region: us-east-1
          AWS_REGION: us-east-1
          AWS_EC2_METADATA_DISABLED: "true"
          AWS_ACCESS_KEY_ID: "fake"
          AWS_SECRET_ACCESS_KEY: "fake"
        working-directory: infra/terraform
        run: terraform plan -input=false -refresh=false
